// Next
import Head from "next/head";

export const Header = (): JSX.Element => {
    return (
        <Head>
            <title>Lit Music</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};
