import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { App } from '../components/app'
import { MainContent } from '../components/main-content'
import styles from '../styles/Home.module.css'

const Home: NextPage = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>React Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App></App>
      {/* <main>
        <h1>
          { process.env.NEXT_PUBLIC_REACT_APP_API}
        </h1>
      </main> */}
    </div>
  )
}

export default Home
