import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { App } from '../components/app'
import { MainContent } from '../components/main-content'
import { ArtistResponse, SongFn, SongResponse } from '../components/types'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

const Home: NextPage<{songs: Array<SongResponse>, artists: Array<ArtistResponse>}> = ({ songs, artists }): JSX.Element => {

  return (
    <div>
      <Head>
        <title>React Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <App songs={songs} artists={artists}></App>
      </main>
    </div>
  )
}

// This function gets called at build time on server-side.
export async function getStaticProps(): Promise<{ props: { songs, artists }}> {

  const songs = await (await fetch(`${process.env.NEXT_PUBLIC_REACT_APP_API}/songs`)).json();
  const artists = await (await fetch(`${process.env.NEXT_PUBLIC_REACT_APP_API}/artists`)).json();
  return {
    props: {
      songs, artists
    }
  }
}

export default Home
